### ISSUE TITLE
Can not Log-In via SSH after the wipefs has finished and the reboot

### ISSUE THREAD

**Issue by BitBlockv6** [joweisberg/openwrt-scripts#1]
yes the title says all. I'am tried this on 23.05.3 OpenWrt yes the description sounded too good to not try.
Anybody has an idea how to log in again ? I am already changed the password via the WebGUI and inserted ssh pub key. no log in ...

**Comment by joweisberg** [comment]
Hello, please check and update with latest git update made now and let me know if you still have the login issue ?
